-- AlterTable
ALTER TABLE `orders` MODIFY `phone` VARCHAR(191) NULL,
    MODIFY `address` VARCHAR(191) NULL,
    MODIFY `city` VARCHAR(191) NULL,
    MODIFY `state` VARCHAR(191) NULL,
    MODIFY `zip` VARCHAR(191) NULL,
    MODIFY `country` VARCHAR(191) NULL;
